// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtcpip_top__Syms.h"


//======================

void Vtcpip_top::trace(VerilatedVcdC* tfp, int, int) {
    tfp->spTrace()->addInitCb(&traceInit, __VlSymsp);
    traceRegister(tfp->spTrace());
}

void Vtcpip_top::traceInit(void* userp, VerilatedVcd* tracep, uint32_t code) {
    // Callback from tracep->open()
    Vtcpip_top__Syms* __restrict vlSymsp = static_cast<Vtcpip_top__Syms*>(userp);
    if (!Verilated::calcUnusedSigs()) {
        VL_FATAL_MT(__FILE__, __LINE__, __FILE__,
                        "Turning on wave traces requires Verilated::traceEverOn(true) call before time 0.");
    }
    vlSymsp->__Vm_baseCode = code;
    tracep->module(vlSymsp->name());
    tracep->scopeEscape(' ');
    Vtcpip_top::traceInitTop(vlSymsp, tracep);
    tracep->scopeEscape('.');
}

//======================


void Vtcpip_top::traceInitTop(void* userp, VerilatedVcd* tracep) {
    Vtcpip_top__Syms* __restrict vlSymsp = static_cast<Vtcpip_top__Syms*>(userp);
    Vtcpip_top* const __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    // Body
    {
        vlTOPp->traceInitSub0(userp, tracep);
    }
}

void Vtcpip_top::traceInitSub0(void* userp, VerilatedVcd* tracep) {
    Vtcpip_top__Syms* __restrict vlSymsp = static_cast<Vtcpip_top__Syms*>(userp);
    Vtcpip_top* const __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    const int c = vlSymsp->__Vm_baseCode;
    if (false && tracep && c) {}  // Prevent unused
    // Body
    {
        tracep->declBit(c+1,"i_sys_clk", false,-1);
        tracep->declBit(c+2,"i_mii_tx_clk", false,-1);
        tracep->declBit(c+3,"i_mii_rx_clk", false,-1);
        tracep->declBit(c+4,"i_rstn", false,-1);
        tracep->declQuad(c+346,"tcpip_top ROUTER_MAC", false,-1, 47,0);
        tracep->declBus(c+348,"tcpip_top ROUTER_IP", false,-1, 31,0);
        tracep->declQuad(c+349,"tcpip_top FPGA_MAC", false,-1, 47,0);
        tracep->declBus(c+351,"tcpip_top FPGA_IP", false,-1, 31,0);
        tracep->declBit(c+5,"tcpip_top i_sys_clk", false,-1);
        tracep->declBit(c+6,"tcpip_top i_mii_tx_clk", false,-1);
        tracep->declBit(c+7,"tcpip_top i_mii_rx_clk", false,-1);
        tracep->declBit(c+8,"tcpip_top i_rstn", false,-1);
        tracep->declBit(c+9,"tcpip_top test_phy_mii_rx_er", false,-1);
        tracep->declBit(c+10,"tcpip_top test_phy_mii_rx_dv", false,-1);
        tracep->declBus(c+11,"tcpip_top test_phy_mii_rx_data", false,-1, 3,0);
        tracep->declBit(c+12,"tcpip_top test_phy_mii_rx_crs", false,-1);
        tracep->declBit(c+13,"tcpip_top test_phy_mii_rx_col", false,-1);
        tracep->declBit(c+14,"tcpip_top test_phy_mii_mdio", false,-1);
        tracep->declBit(c+15,"tcpip_top eth_ctrl_len_fifo_w_en", false,-1);
        tracep->declBus(c+16,"tcpip_top eth_ctrl_frame_len", false,-1, 13,0);
        tracep->declBit(c+17,"tcpip_top eth_ctrl_data_fifo_w_en", false,-1);
        tracep->declBus(c+18,"tcpip_top eth_ctrl_frame_data", false,-1, 3,0);
        tracep->declBit(c+19,"tcpip_top eth_ctrl_mdio", false,-1);
        tracep->declBit(c+20,"tcpip_top eth_fifo_data_fifo_r_done", false,-1);
        tracep->declBit(c+21,"tcpip_top eth_fifo_data_fifo_empty", false,-1);
        tracep->declBit(c+22,"tcpip_top eth_fifo_data_fifo_full", false,-1);
        tracep->declBus(c+23,"tcpip_top eth_fifo_data_fifo_data", false,-1, 3,0);
        tracep->declBit(c+24,"tcpip_top eth_fifo_len_fifo_r_done", false,-1);
        tracep->declBit(c+25,"tcpip_top eth_fifo_len_fifo_empty", false,-1);
        tracep->declBit(c+26,"tcpip_top eth_fifo_len_fifo_full", false,-1);
        tracep->declBus(c+27,"tcpip_top eth_fifo_len_fifo_data", false,-1, 13,0);
        tracep->declBit(c+28,"tcpip_top mac_rx_len_fifo_r_en", false,-1);
        tracep->declBus(c+29,"tcpip_top mac_rx_len_fifo_r_line", false,-1, 4,0);
        tracep->declBit(c+30,"tcpip_top mac_rx_data_fifo_r_en", false,-1);
        tracep->declBit(c+31,"tcpip_top mac_rx_data_fifo_r_stop", false,-1);
        tracep->declBus(c+32,"tcpip_top mac_rx_data_fifo_r_line", false,-1, 13,0);
        tracep->declBus(c+33,"tcpip_top mac_rx_eth_type", false,-1, 15,0);
        tracep->declBit(c+34,"tcpip_top mac_rx_bad_packet_en", false,-1);
        tracep->declBit(c+35,"tcpip_top mac_rx_bad_packet", false,-1);
        tracep->declBit(c+36,"tcpip_top mac_rx_new_packet_en", false,-1);
        tracep->declBus(c+37,"tcpip_top mac_rx_packet_data", false,-1, 3,0);
        tracep->declBit(c+38,"tcpip_top arp_packet", false,-1);
        tracep->declBit(c+39,"tcpip_top ip_packet", false,-1);
        tracep->declBit(c+40,"tcpip_top mac_rx_to_arp_rx_bad_packet_en", false,-1);
        tracep->declBit(c+41,"tcpip_top mac_rx_to_arp_rx_bad_packet", false,-1);
        tracep->declBit(c+42,"tcpip_top mac_rx_to_arp_rx_new_packet_en", false,-1);
        tracep->declBus(c+43,"tcpip_top mac_rx_to_arp_rx_packet_data", false,-1, 3,0);
        tracep->declBit(c+44,"tcpip_top mac_rx_to_ip_rx_bad_packet_en", false,-1);
        tracep->declBit(c+45,"tcpip_top mac_rx_to_ip_rx_bad_packet", false,-1);
        tracep->declBit(c+46,"tcpip_top mac_rx_to_ip_rx_new_packet_en", false,-1);
        tracep->declBus(c+47,"tcpip_top mac_rx_to_ip_rx_packet_data", false,-1, 3,0);
        tracep->declBit(c+48,"tcpip_top arp_rx_new_packet", false,-1);
        tracep->declBit(c+49,"tcpip_top arp_rx_need_reply", false,-1);
        tracep->declBus(c+50,"tcpip_top arp_rx_receive_ip", false,-1, 31,0);
        tracep->declQuad(c+51,"tcpip_top arp_rx_receive_mac", false,-1, 47,0);
        tracep->declBit(c+53,"tcpip_top arp_rx_arp_rx_busy", false,-1);
        tracep->declBit(c+54,"tcpip_top arp_tx_lookup_done", false,-1);
        tracep->declBit(c+55,"tcpip_top arp_tx_lookup_result", false,-1);
        tracep->declQuad(c+56,"tcpip_top arp_tx_lookup_mac", false,-1, 47,0);
        tracep->declBit(c+58,"tcpip_top arp_tx_arp_packet_en", false,-1);
        tracep->declBus(c+59,"tcpip_top arp_tx_arp_packet_data", false,-1, 3,0);
        tracep->declBit(c+60,"tcpip_top arp_tx_arp_tx_busy", false,-1);
        tracep->declBit(c+61,"tcpip_top ip_rx_drop_packet", false,-1);
        tracep->declBit(c+62,"tcpip_top ip_rx_ip_rx_busy", false,-1);
        tracep->declBit(c+63,"tcpip_top ip_rx_new_segment", false,-1);
        tracep->declBus(c+64,"tcpip_top ip_rx_segment_type", false,-1, 7,0);
        tracep->declBus(c+65,"tcpip_top ip_rx_segment_data", false,-1, 3,0);
        tracep->declBit(c+66,"tcpip_top test_phy0 i_rx_clk", false,-1);
        tracep->declBit(c+67,"tcpip_top test_phy0 i_tx_clk", false,-1);
        tracep->declBit(c+68,"tcpip_top test_phy0 i_rstn", false,-1);
        tracep->declBit(c+69,"tcpip_top test_phy0 i_mii_tx_er", false,-1);
        tracep->declBit(c+70,"tcpip_top test_phy0 i_mii_tx_en", false,-1);
        tracep->declBus(c+71,"tcpip_top test_phy0 i_mii_tx_data", false,-1, 3,0);
        tracep->declBit(c+72,"tcpip_top test_phy0 i_mdc", false,-1);
        tracep->declBit(c+73,"tcpip_top test_phy0 i_mdio", false,-1);
        tracep->declBit(c+74,"tcpip_top test_phy0 o_mii_rx_er", false,-1);
        tracep->declBit(c+75,"tcpip_top test_phy0 o_mii_rx_dv", false,-1);
        tracep->declBus(c+76,"tcpip_top test_phy0 o_mii_rx_data", false,-1, 3,0);
        tracep->declBit(c+77,"tcpip_top test_phy0 o_mii_rx_crs", false,-1);
        tracep->declBit(c+78,"tcpip_top test_phy0 o_mii_rx_col", false,-1);
        tracep->declBit(c+79,"tcpip_top test_phy0 o_mii_mdio", false,-1);
        tracep->declBus(c+80,"tcpip_top test_phy0 tx_index", false,-1, 31,0);
        tracep->declBus(c+81,"tcpip_top test_phy0 rx_index", false,-1, 31,0);
        tracep->declBus(c+82,"tcpip_top test_phy0 frame_done", false,-1, 2,0);
        tracep->declBit(c+83,"tcpip_top eth_rx_ctrl0 i_sys_clk", false,-1);
        tracep->declBit(c+84,"tcpip_top eth_rx_ctrl0 i_rx_clk", false,-1);
        tracep->declBit(c+85,"tcpip_top eth_rx_ctrl0 i_rstn", false,-1);
        tracep->declBit(c+86,"tcpip_top eth_rx_ctrl0 i_rx_dv", false,-1);
        tracep->declBus(c+87,"tcpip_top eth_rx_ctrl0 i_rx_data", false,-1, 3,0);
        tracep->declBit(c+88,"tcpip_top eth_rx_ctrl0 i_rx_er", false,-1);
        tracep->declBit(c+89,"tcpip_top eth_rx_ctrl0 i_rx_col", false,-1);
        tracep->declBit(c+90,"tcpip_top eth_rx_ctrl0 i_rx_crs", false,-1);
        tracep->declBit(c+91,"tcpip_top eth_rx_ctrl0 i_mdio", false,-1);
        tracep->declBit(c+92,"tcpip_top eth_rx_ctrl0 o_len_fifo_w_en", false,-1);
        tracep->declBus(c+93,"tcpip_top eth_rx_ctrl0 o_frame_len", false,-1, 13,0);
        tracep->declBit(c+94,"tcpip_top eth_rx_ctrl0 o_data_fifo_w_en", false,-1);
        tracep->declBus(c+95,"tcpip_top eth_rx_ctrl0 o_frame_data", false,-1, 3,0);
        tracep->declBit(c+96,"tcpip_top eth_rx_ctrl0 o_mdio", false,-1);
        tracep->declBit(c+97,"tcpip_top eth_rx_ctrl0 prev_rx_dv", false,-1);
        tracep->declBus(c+98,"tcpip_top eth_rx_ctrl0 frame_lenth", false,-1, 13,0);
        tracep->declBit(c+99,"tcpip_top eth_rx_ctrl0 rx_trans_start", false,-1);
        tracep->declBit(c+100,"tcpip_top eth_rx_ctrl0 rx_trans_done", false,-1);
        tracep->declBit(c+101,"tcpip_top eth_fifo0 i_rx_clk", false,-1);
        tracep->declBit(c+102,"tcpip_top eth_fifo0 i_sys_clk", false,-1);
        tracep->declBit(c+103,"tcpip_top eth_fifo0 i_rstn", false,-1);
        tracep->declBit(c+104,"tcpip_top eth_fifo0 i_data_fifo_w_en", false,-1);
        tracep->declBus(c+105,"tcpip_top eth_fifo0 i_data_fifo_data", false,-1, 3,0);
        tracep->declBit(c+106,"tcpip_top eth_fifo0 i_data_fifo_r_en", false,-1);
        tracep->declBit(c+107,"tcpip_top eth_fifo0 i_data_fifo_r_stop", false,-1);
        tracep->declBus(c+108,"tcpip_top eth_fifo0 i_data_fifo_r_line", false,-1, 13,0);
        tracep->declBit(c+109,"tcpip_top eth_fifo0 i_len_fifo_w_en", false,-1);
        tracep->declBus(c+110,"tcpip_top eth_fifo0 i_len_fifo_data", false,-1, 13,0);
        tracep->declBit(c+111,"tcpip_top eth_fifo0 i_len_fifo_r_en", false,-1);
        tracep->declBus(c+112,"tcpip_top eth_fifo0 i_len_fifo_r_line", false,-1, 4,0);
        tracep->declBit(c+113,"tcpip_top eth_fifo0 o_data_fifo_r_done", false,-1);
        tracep->declBit(c+114,"tcpip_top eth_fifo0 o_data_fifo_empty", false,-1);
        tracep->declBit(c+115,"tcpip_top eth_fifo0 o_data_fifo_full", false,-1);
        tracep->declBus(c+116,"tcpip_top eth_fifo0 o_data_fifo_data", false,-1, 3,0);
        tracep->declBit(c+117,"tcpip_top eth_fifo0 o_len_fifo_r_done", false,-1);
        tracep->declBit(c+118,"tcpip_top eth_fifo0 o_len_fifo_empty", false,-1);
        tracep->declBit(c+119,"tcpip_top eth_fifo0 o_len_fifo_full", false,-1);
        tracep->declBus(c+120,"tcpip_top eth_fifo0 o_len_fifo_data", false,-1, 13,0);
        tracep->declBus(c+352,"tcpip_top eth_fifo0 eth_data_fifo0 DATA_WIDTH", false,-1, 31,0);
        tracep->declBus(c+353,"tcpip_top eth_fifo0 eth_data_fifo0 FIFO_DEPTH", false,-1, 31,0);
        tracep->declBit(c+121,"tcpip_top eth_fifo0 eth_data_fifo0 i_rx_clk", false,-1);
        tracep->declBit(c+122,"tcpip_top eth_fifo0 eth_data_fifo0 i_sys_clk", false,-1);
        tracep->declBit(c+123,"tcpip_top eth_fifo0 eth_data_fifo0 i_rstn", false,-1);
        tracep->declBit(c+124,"tcpip_top eth_fifo0 eth_data_fifo0 i_fifo_w_en", false,-1);
        tracep->declBus(c+125,"tcpip_top eth_fifo0 eth_data_fifo0 i_data", false,-1, 3,0);
        tracep->declBit(c+126,"tcpip_top eth_fifo0 eth_data_fifo0 i_fifo_r_en", false,-1);
        tracep->declBit(c+127,"tcpip_top eth_fifo0 eth_data_fifo0 i_fifo_r_stop", false,-1);
        tracep->declBus(c+128,"tcpip_top eth_fifo0 eth_data_fifo0 i_fifo_r_len", false,-1, 13,0);
        tracep->declBit(c+129,"tcpip_top eth_fifo0 eth_data_fifo0 o_fifo_r_done", false,-1);
        tracep->declBit(c+130,"tcpip_top eth_fifo0 eth_data_fifo0 o_fifo_empty", false,-1);
        tracep->declBit(c+131,"tcpip_top eth_fifo0 eth_data_fifo0 o_fifo_full", false,-1);
        tracep->declBus(c+132,"tcpip_top eth_fifo0 eth_data_fifo0 o_data", false,-1, 3,0);
        tracep->declBus(c+133,"tcpip_top eth_fifo0 eth_data_fifo0 w_ptr", false,-1, 13,0);
        tracep->declBus(c+134,"tcpip_top eth_fifo0 eth_data_fifo0 r_ptr", false,-1, 13,0);
        tracep->declBus(c+135,"tcpip_top eth_fifo0 eth_data_fifo0 r_start_ptr", false,-1, 13,0);
        tracep->declBit(c+136,"tcpip_top eth_fifo0 eth_data_fifo0 last_read", false,-1);
        tracep->declBus(c+137,"tcpip_top eth_fifo0 eth_data_fifo0 i", false,-1, 31,0);
        tracep->declBus(c+138,"tcpip_top eth_fifo0 eth_data_fifo0 end_line", false,-1, 13,0);
        tracep->declBus(c+139,"tcpip_top eth_fifo0 eth_data_fifo0 fifo_r_end_line", false,-1, 13,0);
        tracep->declBus(c+354,"tcpip_top eth_fifo0 eth_len_fifo1 DATA_WIDTH", false,-1, 31,0);
        tracep->declBus(c+355,"tcpip_top eth_fifo0 eth_len_fifo1 FIFO_DEPTH", false,-1, 31,0);
        tracep->declBit(c+140,"tcpip_top eth_fifo0 eth_len_fifo1 i_rx_clk", false,-1);
        tracep->declBit(c+141,"tcpip_top eth_fifo0 eth_len_fifo1 i_sys_clk", false,-1);
        tracep->declBit(c+142,"tcpip_top eth_fifo0 eth_len_fifo1 i_rstn", false,-1);
        tracep->declBit(c+143,"tcpip_top eth_fifo0 eth_len_fifo1 i_fifo_w_en", false,-1);
        tracep->declBus(c+144,"tcpip_top eth_fifo0 eth_len_fifo1 i_data", false,-1, 13,0);
        tracep->declBit(c+145,"tcpip_top eth_fifo0 eth_len_fifo1 i_fifo_r_en", false,-1);
        tracep->declBit(c+146,"tcpip_top eth_fifo0 eth_len_fifo1 i_fifo_r_stop", false,-1);
        tracep->declBus(c+147,"tcpip_top eth_fifo0 eth_len_fifo1 i_fifo_r_len", false,-1, 4,0);
        tracep->declBit(c+148,"tcpip_top eth_fifo0 eth_len_fifo1 o_fifo_r_done", false,-1);
        tracep->declBit(c+149,"tcpip_top eth_fifo0 eth_len_fifo1 o_fifo_empty", false,-1);
        tracep->declBit(c+150,"tcpip_top eth_fifo0 eth_len_fifo1 o_fifo_full", false,-1);
        tracep->declBus(c+151,"tcpip_top eth_fifo0 eth_len_fifo1 o_data", false,-1, 13,0);
        {int i; for (i=0; i<24; i++) {
                tracep->declBus(c+152+i*1,"tcpip_top eth_fifo0 eth_len_fifo1 fifo_q", true,(i+0), 13,0);}}
        tracep->declBus(c+176,"tcpip_top eth_fifo0 eth_len_fifo1 w_ptr", false,-1, 4,0);
        tracep->declBus(c+177,"tcpip_top eth_fifo0 eth_len_fifo1 r_ptr", false,-1, 4,0);
        tracep->declBus(c+178,"tcpip_top eth_fifo0 eth_len_fifo1 r_start_ptr", false,-1, 4,0);
        tracep->declBit(c+179,"tcpip_top eth_fifo0 eth_len_fifo1 last_read", false,-1);
        tracep->declBus(c+180,"tcpip_top eth_fifo0 eth_len_fifo1 i", false,-1, 31,0);
        tracep->declBus(c+181,"tcpip_top eth_fifo0 eth_len_fifo1 end_line", false,-1, 4,0);
        tracep->declBus(c+182,"tcpip_top eth_fifo0 eth_len_fifo1 fifo_r_end_line", false,-1, 4,0);
        tracep->declQuad(c+346,"tcpip_top mac_rx0 ROUTER_MAC", false,-1, 47,0);
        tracep->declQuad(c+349,"tcpip_top mac_rx0 FPGA_MAC", false,-1, 47,0);
        tracep->declBit(c+183,"tcpip_top mac_rx0 i_sys_clk", false,-1);
        tracep->declBit(c+184,"tcpip_top mac_rx0 i_rstn", false,-1);
        tracep->declBit(c+185,"tcpip_top mac_rx0 i_len_fifo_empty", false,-1);
        tracep->declBit(c+186,"tcpip_top mac_rx0 i_len_r_done", false,-1);
        tracep->declBit(c+187,"tcpip_top mac_rx0 i_data_r_done", false,-1);
        tracep->declBus(c+188,"tcpip_top mac_rx0 i_frame_len", false,-1, 13,0);
        tracep->declBus(c+189,"tcpip_top mac_rx0 i_frame_data", false,-1, 3,0);
        tracep->declBit(c+190,"tcpip_top mac_rx0 i_arp_rx_busy", false,-1);
        tracep->declBit(c+191,"tcpip_top mac_rx0 i_ip_rx_busy", false,-1);
        tracep->declBit(c+192,"tcpip_top mac_rx0 i_ip_rx_drop", false,-1);
        tracep->declBit(c+193,"tcpip_top mac_rx0 o_len_fifo_r_en", false,-1);
        tracep->declBus(c+194,"tcpip_top mac_rx0 o_len_fifo_r_line", false,-1, 4,0);
        tracep->declBit(c+195,"tcpip_top mac_rx0 o_data_fifo_r_en", false,-1);
        tracep->declBus(c+196,"tcpip_top mac_rx0 o_data_fifo_r_line", false,-1, 13,0);
        tracep->declBit(c+197,"tcpip_top mac_rx0 o_data_fifo_r_stop", false,-1);
        tracep->declBus(c+198,"tcpip_top mac_rx0 o_eth_type", false,-1, 15,0);
        tracep->declBit(c+199,"tcpip_top mac_rx0 o_bad_packet_en", false,-1);
        tracep->declBit(c+200,"tcpip_top mac_rx0 o_bad_packet", false,-1);
        tracep->declBit(c+201,"tcpip_top mac_rx0 o_new_packet_en", false,-1);
        tracep->declBus(c+202,"tcpip_top mac_rx0 o_packet_data", false,-1, 3,0);
        tracep->declBus(c+356,"tcpip_top mac_rx0 IDLE_STAGE", false,-1, 1,0);
        tracep->declBus(c+357,"tcpip_top mac_rx0 LEN_STAGE", false,-1, 1,0);
        tracep->declBus(c+358,"tcpip_top mac_rx0 PARSE_STAGE", false,-1, 1,0);
        tracep->declBus(c+359,"tcpip_top mac_rx0 CHECK_STAGE", false,-1, 1,0);
        tracep->declBus(c+203,"tcpip_top mac_rx0 CUR_STAGE", false,-1, 1,0);
        tracep->declBus(c+204,"tcpip_top mac_rx0 NXT_STAGE", false,-1, 1,0);
        tracep->declBus(c+205,"tcpip_top mac_rx0 frame_recieved_cnt", false,-1, 13,0);
        tracep->declQuad(c+206,"tcpip_top mac_rx0 src_mac_latch", false,-1, 47,0);
        tracep->declQuad(c+208,"tcpip_top mac_rx0 dst_mac_latch", false,-1, 47,0);
        tracep->declBus(c+210,"tcpip_top mac_rx0 eth_type_latch", false,-1, 15,0);
        tracep->declBit(c+211,"tcpip_top mac_rx0 eth_parse_done", false,-1);
        tracep->declBus(c+212,"tcpip_top mac_rx0 frame_len_latch", false,-1, 13,0);
        tracep->declBit(c+213,"tcpip_top mac_rx0 ip_rx_clear", false,-1);
        tracep->declBit(c+214,"tcpip_top mac_rx0 my_frame", false,-1);
        tracep->declBit(c+215,"tcpip_top mac_rx0 fcs_data_start", false,-1);
        tracep->declBit(c+216,"tcpip_top mac_rx0 fcs_check", false,-1);
        tracep->declBit(c+217,"tcpip_top mac_rx0 fcs_en", false,-1);
        tracep->declBit(c+218,"tcpip_top mac_rx0 fcs_comp_done", false,-1);
        tracep->declBus(c+219,"tcpip_top mac_rx0 fcs_comp", false,-1, 31,0);
        tracep->declBus(c+220,"tcpip_top mac_rx0 frame_prev_latch", false,-1, 3,0);
        tracep->declBit(c+221,"tcpip_top mac_rx0 fcs_data_cnt", false,-1);
        tracep->declBus(c+222,"tcpip_top mac_rx0 fcs_data", false,-1, 7,0);
        tracep->declBit(c+223,"tcpip_top mac_rx0 crc32_0 i_sys_clk", false,-1);
        tracep->declBit(c+224,"tcpip_top mac_rx0 crc32_0 i_rstn", false,-1);
        tracep->declBus(c+225,"tcpip_top mac_rx0 crc32_0 i_data", false,-1, 7,0);
        tracep->declBit(c+226,"tcpip_top mac_rx0 crc32_0 i_crc_en", false,-1);
        tracep->declBit(c+227,"tcpip_top mac_rx0 crc32_0 i_crc_done", false,-1);
        tracep->declBus(c+228,"tcpip_top mac_rx0 crc32_0 o_fcs", false,-1, 31,0);
        tracep->declBus(c+229,"tcpip_top mac_rx0 crc32_0 lfsr_q", false,-1, 31,0);
        tracep->declBus(c+230,"tcpip_top mac_rx0 crc32_0 lfsr_c", false,-1, 31,0);
        tracep->declBus(c+351,"tcpip_top arp_rx0 FPGA_IP", false,-1, 31,0);
        tracep->declQuad(c+349,"tcpip_top arp_rx0 FPGA_MAC", false,-1, 47,0);
        tracep->declBit(c+231,"tcpip_top arp_rx0 i_sys_clk", false,-1);
        tracep->declBit(c+232,"tcpip_top arp_rx0 i_rstn", false,-1);
        tracep->declBit(c+233,"tcpip_top arp_rx0 i_new_packet", false,-1);
        tracep->declBus(c+234,"tcpip_top arp_rx0 i_packet_data", false,-1, 3,0);
        tracep->declBit(c+235,"tcpip_top arp_rx0 i_bad_packet_en", false,-1);
        tracep->declBit(c+236,"tcpip_top arp_rx0 i_bad_packet", false,-1);
        tracep->declBit(c+237,"tcpip_top arp_rx0 i_arp_tx_busy", false,-1);
        tracep->declBit(c+238,"tcpip_top arp_rx0 o_new_packet", false,-1);
        tracep->declBit(c+239,"tcpip_top arp_rx0 o_arp_need_reply", false,-1);
        tracep->declBus(c+240,"tcpip_top arp_rx0 o_arp_receive_ip", false,-1, 31,0);
        tracep->declQuad(c+241,"tcpip_top arp_rx0 o_arp_receive_mac", false,-1, 47,0);
        tracep->declBit(c+243,"tcpip_top arp_rx0 o_arp_rx_busy", false,-1);
        tracep->declBus(c+356,"tcpip_top arp_rx0 IDLE_STAGE", false,-1, 1,0);
        tracep->declBus(c+357,"tcpip_top arp_rx0 GATHER_STAGE", false,-1, 1,0);
        tracep->declBus(c+358,"tcpip_top arp_rx0 TRANS_STAGE", false,-1, 1,0);
        tracep->declBus(c+244,"tcpip_top arp_rx0 hardware_type_latch", false,-1, 15,0);
        tracep->declBus(c+245,"tcpip_top arp_rx0 protocol_type_latch", false,-1, 15,0);
        tracep->declBus(c+246,"tcpip_top arp_rx0 opcode_latch", false,-1, 15,0);
        tracep->declQuad(c+247,"tcpip_top arp_rx0 src_mac_latch", false,-1, 47,0);
        tracep->declBus(c+249,"tcpip_top arp_rx0 src_ip_latch", false,-1, 31,0);
        tracep->declBus(c+250,"tcpip_top arp_rx0 dest_ip_latch", false,-1, 31,0);
        tracep->declBus(c+251,"tcpip_top arp_rx0 arp_recieve_cnt", false,-1, 5,0);
        tracep->declBit(c+252,"tcpip_top arp_rx0 new_packet_latch", false,-1);
        tracep->declBus(c+253,"tcpip_top arp_rx0 CUR_STAGE", false,-1, 1,0);
        tracep->declBus(c+254,"tcpip_top arp_rx0 NXT_STAGE", false,-1, 1,0);
        tracep->declBit(c+255,"tcpip_top arp_rx0 correct_packet", false,-1);
        tracep->declBit(c+256,"tcpip_top arp_rx0 gather_done", false,-1);
        tracep->declBit(c+257,"tcpip_top arp_rx0 arp_done", false,-1);
        tracep->declBit(c+258,"tcpip_top arp_rx0 my_arp_packet", false,-1);
        tracep->declBit(c+259,"tcpip_top arp_rx0 arp_request", false,-1);
        tracep->declBit(c+260,"tcpip_top arp_rx0 arp_reply", false,-1);
        tracep->declBus(c+348,"tcpip_top arp_tx0 FPGA_IP", false,-1, 31,0);
        tracep->declQuad(c+349,"tcpip_top arp_tx0 FPGA_MAC", false,-1, 47,0);
        tracep->declBus(c+351,"tcpip_top arp_tx0 ROUTER_IP", false,-1, 31,0);
        tracep->declQuad(c+346,"tcpip_top arp_tx0 ROUTER_MAC", false,-1, 47,0);
        tracep->declBit(c+261,"tcpip_top arp_tx0 i_sys_clk", false,-1);
        tracep->declBit(c+262,"tcpip_top arp_tx0 i_rstn", false,-1);
        tracep->declBit(c+263,"tcpip_top arp_tx0 i_lookup_en", false,-1);
        tracep->declBus(c+264,"tcpip_top arp_tx0 i_lookup_ip", false,-1, 31,0);
        tracep->declBit(c+265,"tcpip_top arp_tx0 i_rx_new_packet", false,-1);
        tracep->declBit(c+266,"tcpip_top arp_tx0 i_need_reply", false,-1);
        tracep->declBus(c+267,"tcpip_top arp_tx0 i_receive_ip", false,-1, 31,0);
        tracep->declQuad(c+268,"tcpip_top arp_tx0 i_receive_mac", false,-1, 47,0);
        tracep->declBit(c+270,"tcpip_top arp_tx0 o_lookup_done", false,-1);
        tracep->declBit(c+271,"tcpip_top arp_tx0 o_lookup_result", false,-1);
        tracep->declQuad(c+272,"tcpip_top arp_tx0 o_lookup_mac", false,-1, 47,0);
        tracep->declBit(c+274,"tcpip_top arp_tx0 o_arp_packet_en", false,-1);
        tracep->declBus(c+275,"tcpip_top arp_tx0 o_arp_packet_data", false,-1, 3,0);
        tracep->declBit(c+276,"tcpip_top arp_tx0 o_arp_tx_busy", false,-1);
        tracep->declBus(c+356,"tcpip_top arp_tx0 IDLE_STAGE", false,-1, 1,0);
        tracep->declBus(c+357,"tcpip_top arp_tx0 LOOKUP_STAGE", false,-1, 1,0);
        tracep->declBus(c+358,"tcpip_top arp_tx0 SEND_STAGE", false,-1, 1,0);
        tracep->declBus(c+277,"tcpip_top arp_tx0 CUR_STAGE", false,-1, 1,0);
        tracep->declBus(c+278,"tcpip_top arp_tx0 NXT_STAGE", false,-1, 1,0);
        tracep->declQuad(c+279,"tcpip_top arp_tx0 src_mac_latch", false,-1, 47,0);
        tracep->declBus(c+281,"tcpip_top arp_tx0 src_ip_latch", false,-1, 31,0);
        tracep->declBit(c+282,"tcpip_top arp_tx0 mac_unkwown", false,-1);
        tracep->declBus(c+283,"tcpip_top arp_tx0 lookup_ip_latch", false,-1, 31,0);
        tracep->declBit(c+284,"tcpip_top arp_tx0 arp_cache_w_en", false,-1);
        tracep->declBus(c+285,"tcpip_top arp_tx0 arp_send_cnt", false,-1, 5,0);
        tracep->declBit(c+286,"tcpip_top arp_tx0 arp_send_done", false,-1);
        tracep->declBus(c+360,"tcpip_top arp_tx0 arp_cache0 ENTRY_DEPTH", false,-1, 2,0);
        tracep->declBus(c+351,"tcpip_top arp_tx0 arp_cache0 ROUTER_IP", false,-1, 31,0);
        tracep->declQuad(c+346,"tcpip_top arp_tx0 arp_cache0 ROUTER_MAC", false,-1, 47,0);
        tracep->declBit(c+287,"tcpip_top arp_tx0 arp_cache0 i_sys_clk", false,-1);
        tracep->declBit(c+288,"tcpip_top arp_tx0 arp_cache0 i_rstn", false,-1);
        tracep->declBit(c+289,"tcpip_top arp_tx0 arp_cache0 i_lookup_en", false,-1);
        tracep->declBus(c+290,"tcpip_top arp_tx0 arp_cache0 i_lookup_ip", false,-1, 31,0);
        tracep->declBit(c+291,"tcpip_top arp_tx0 arp_cache0 i_cache_w_en", false,-1);
        tracep->declBus(c+292,"tcpip_top arp_tx0 arp_cache0 i_cache_w_ip", false,-1, 31,0);
        tracep->declQuad(c+293,"tcpip_top arp_tx0 arp_cache0 i_cache_w_mac", false,-1, 47,0);
        tracep->declBit(c+295,"tcpip_top arp_tx0 arp_cache0 o_lookup_done", false,-1);
        tracep->declBit(c+296,"tcpip_top arp_tx0 arp_cache0 o_lookup_result", false,-1);
        tracep->declQuad(c+297,"tcpip_top arp_tx0 arp_cache0 o_lookup_mac", false,-1, 47,0);
        {int i; for (i=0; i<5; i++) {
                tracep->declQuad(c+299+i*2,"tcpip_top arp_tx0 arp_cache0 arp_mac_queue", true,(i+0), 47,0);}}
        {int i; for (i=0; i<5; i++) {
                tracep->declBus(c+309+i*1,"tcpip_top arp_tx0 arp_cache0 arp_ip_queue", true,(i+0), 31,0);}}
        tracep->declBus(c+314,"tcpip_top arp_tx0 arp_cache0 queue_w_ptr", false,-1, 2,0);
        tracep->declBus(c+315,"tcpip_top arp_tx0 arp_cache0 a", false,-1, 2,0);
        tracep->declBus(c+316,"tcpip_top arp_tx0 arp_cache0 b", false,-1, 31,0);
        tracep->declBus(c+348,"tcpip_top ip_rx0 FPGA_IP", false,-1, 31,0);
        tracep->declBit(c+317,"tcpip_top ip_rx0 i_sys_clk", false,-1);
        tracep->declBit(c+318,"tcpip_top ip_rx0 i_rstn", false,-1);
        tracep->declBit(c+319,"tcpip_top ip_rx0 i_new_packet", false,-1);
        tracep->declBus(c+320,"tcpip_top ip_rx0 i_ip_data", false,-1, 3,0);
        tracep->declBit(c+321,"tcpip_top ip_rx0 i_bad_packet_en", false,-1);
        tracep->declBit(c+322,"tcpip_top ip_rx0 i_bad_packet", false,-1);
        tracep->declBit(c+323,"tcpip_top ip_rx0 o_drop_packet", false,-1);
        tracep->declBit(c+324,"tcpip_top ip_rx0 o_ip_rx_busy", false,-1);
        tracep->declBit(c+325,"tcpip_top ip_rx0 o_new_segment", false,-1);
        tracep->declBus(c+326,"tcpip_top ip_rx0 o_segment_type", false,-1, 7,0);
        tracep->declBus(c+327,"tcpip_top ip_rx0 o_segment_data", false,-1, 3,0);
        tracep->declBus(c+361,"tcpip_top ip_rx0 TYPE_TCP", false,-1, 7,0);
        tracep->declBus(c+362,"tcpip_top ip_rx0 TYPE_UDP", false,-1, 7,0);
        tracep->declBus(c+363,"tcpip_top ip_rx0 TYPE_ICMP", false,-1, 7,0);
        tracep->declBus(c+356,"tcpip_top ip_rx0 IDLE_STAGE", false,-1, 1,0);
        tracep->declBus(c+357,"tcpip_top ip_rx0 HEADER_STAGE", false,-1, 1,0);
        tracep->declBus(c+358,"tcpip_top ip_rx0 TRANS_STAGE", false,-1, 1,0);
        tracep->declBus(c+328,"tcpip_top ip_rx0 CUR_STAGE", false,-1, 1,0);
        tracep->declBus(c+329,"tcpip_top ip_rx0 NXT_STAGE", false,-1, 1,0);
        tracep->declBus(c+330,"tcpip_top ip_rx0 ip_ver_latch", false,-1, 3,0);
        tracep->declBus(c+331,"tcpip_top ip_rx0 ihl_latch", false,-1, 3,0);
        tracep->declBus(c+332,"tcpip_top ip_rx0 flag_latch", false,-1, 2,0);
        tracep->declBus(c+333,"tcpip_top ip_rx0 frag_offset_latch", false,-1, 12,0);
        tracep->declBus(c+334,"tcpip_top ip_rx0 protocol_latch", false,-1, 7,0);
        tracep->declBus(c+335,"tcpip_top ip_rx0 checksum_latch", false,-1, 15,0);
        tracep->declBus(c+336,"tcpip_top ip_rx0 src_ip_latch", false,-1, 31,0);
        tracep->declBus(c+337,"tcpip_top ip_rx0 dst_ip_latch", false,-1, 31,0);
        tracep->declBus(c+338,"tcpip_top ip_rx0 rx_cnt", false,-1, 13,0);
        tracep->declBus(c+339,"tcpip_top ip_rx0 checksum_temp", false,-1, 15,0);
        tracep->declBus(c+340,"tcpip_top ip_rx0 checksum_sum", false,-1, 15,0);
        tracep->declBus(c+341,"tcpip_top ip_rx0 checksum_cnt", false,-1, 1,0);
        tracep->declBus(c+342,"tcpip_top ip_rx0 checksum_extend", false,-1, 16,0);
        tracep->declBit(c+343,"tcpip_top ip_rx0 packet_en_prev", false,-1);
        tracep->declBit(c+344,"tcpip_top ip_rx0 header_done", false,-1);
        tracep->declBit(c+345,"tcpip_top ip_rx0 check_failed", false,-1);
    }
}

void Vtcpip_top::traceRegister(VerilatedVcd* tracep) {
    // Body
    {
        tracep->addFullCb(&traceFullTop0, __VlSymsp);
        tracep->addChgCb(&traceChgTop0, __VlSymsp);
        tracep->addCleanupCb(&traceCleanup, __VlSymsp);
    }
}

void Vtcpip_top::traceFullTop0(void* userp, VerilatedVcd* tracep) {
    Vtcpip_top__Syms* __restrict vlSymsp = static_cast<Vtcpip_top__Syms*>(userp);
    Vtcpip_top* const __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    // Body
    {
        vlTOPp->traceFullSub0(userp, tracep);
    }
}

void Vtcpip_top::traceFullSub0(void* userp, VerilatedVcd* tracep) {
    Vtcpip_top__Syms* __restrict vlSymsp = static_cast<Vtcpip_top__Syms*>(userp);
    Vtcpip_top* const __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    vluint32_t* const oldp = tracep->oldp(vlSymsp->__Vm_baseCode);
    if (false && oldp) {}  // Prevent unused
    // Body
    {
        tracep->fullBit(oldp+1,(vlTOPp->i_sys_clk));
        tracep->fullBit(oldp+2,(vlTOPp->i_mii_tx_clk));
        tracep->fullBit(oldp+3,(vlTOPp->i_mii_rx_clk));
        tracep->fullBit(oldp+4,(vlTOPp->i_rstn));
        tracep->fullBit(oldp+5,(vlTOPp->tcpip_top__DOT__i_sys_clk));
        tracep->fullBit(oldp+6,(vlTOPp->tcpip_top__DOT__i_mii_tx_clk));
        tracep->fullBit(oldp+7,(vlTOPp->tcpip_top__DOT__i_mii_rx_clk));
        tracep->fullBit(oldp+8,(vlTOPp->tcpip_top__DOT__i_rstn));
        tracep->fullBit(oldp+9,(vlTOPp->tcpip_top__DOT__test_phy_mii_rx_er));
        tracep->fullBit(oldp+10,(vlTOPp->tcpip_top__DOT__test_phy_mii_rx_dv));
        tracep->fullCData(oldp+11,(vlTOPp->tcpip_top__DOT__test_phy_mii_rx_data),4);
        tracep->fullBit(oldp+12,(vlTOPp->tcpip_top__DOT__test_phy_mii_rx_crs));
        tracep->fullBit(oldp+13,(vlTOPp->tcpip_top__DOT__test_phy_mii_rx_col));
        tracep->fullBit(oldp+14,(vlTOPp->tcpip_top__DOT__test_phy_mii_mdio));
        tracep->fullBit(oldp+15,(vlTOPp->tcpip_top__DOT__eth_ctrl_len_fifo_w_en));
        tracep->fullSData(oldp+16,(vlTOPp->tcpip_top__DOT__eth_ctrl_frame_len),14);
        tracep->fullBit(oldp+17,(vlTOPp->tcpip_top__DOT__eth_ctrl_data_fifo_w_en));
        tracep->fullCData(oldp+18,(vlTOPp->tcpip_top__DOT__eth_ctrl_frame_data),4);
        tracep->fullBit(oldp+19,(vlTOPp->tcpip_top__DOT__eth_ctrl_mdio));
        tracep->fullBit(oldp+20,(vlTOPp->tcpip_top__DOT__eth_fifo_data_fifo_r_done));
        tracep->fullBit(oldp+21,(vlTOPp->tcpip_top__DOT__eth_fifo_data_fifo_empty));
        tracep->fullBit(oldp+22,(vlTOPp->tcpip_top__DOT__eth_fifo_data_fifo_full));
        tracep->fullCData(oldp+23,(vlTOPp->tcpip_top__DOT__eth_fifo_data_fifo_data),4);
        tracep->fullBit(oldp+24,(vlTOPp->tcpip_top__DOT__eth_fifo_len_fifo_r_done));
        tracep->fullBit(oldp+25,(vlTOPp->tcpip_top__DOT__eth_fifo_len_fifo_empty));
        tracep->fullBit(oldp+26,(vlTOPp->tcpip_top__DOT__eth_fifo_len_fifo_full));
        tracep->fullSData(oldp+27,(vlTOPp->tcpip_top__DOT__eth_fifo_len_fifo_data),14);
        tracep->fullBit(oldp+28,(vlTOPp->tcpip_top__DOT__mac_rx_len_fifo_r_en));
        tracep->fullCData(oldp+29,(vlTOPp->tcpip_top__DOT__mac_rx_len_fifo_r_line),5);
        tracep->fullBit(oldp+30,(vlTOPp->tcpip_top__DOT__mac_rx_data_fifo_r_en));
        tracep->fullBit(oldp+31,(vlTOPp->tcpip_top__DOT__mac_rx_data_fifo_r_stop));
        tracep->fullSData(oldp+32,(vlTOPp->tcpip_top__DOT__mac_rx_data_fifo_r_line),14);
        tracep->fullSData(oldp+33,(vlTOPp->tcpip_top__DOT__mac_rx_eth_type),16);
        tracep->fullBit(oldp+34,(vlTOPp->tcpip_top__DOT__mac_rx_bad_packet_en));
        tracep->fullBit(oldp+35,(vlTOPp->tcpip_top__DOT__mac_rx_bad_packet));
        tracep->fullBit(oldp+36,(vlTOPp->tcpip_top__DOT__mac_rx_new_packet_en));
        tracep->fullCData(oldp+37,(vlTOPp->tcpip_top__DOT__mac_rx_packet_data),4);
        tracep->fullBit(oldp+38,(vlTOPp->tcpip_top__DOT__arp_packet));
        tracep->fullBit(oldp+39,(vlTOPp->tcpip_top__DOT__ip_packet));
        tracep->fullBit(oldp+40,(vlTOPp->tcpip_top__DOT__mac_rx_to_arp_rx_bad_packet_en));
        tracep->fullBit(oldp+41,(vlTOPp->tcpip_top__DOT__mac_rx_to_arp_rx_bad_packet));
        tracep->fullBit(oldp+42,(vlTOPp->tcpip_top__DOT__mac_rx_to_arp_rx_new_packet_en));
        tracep->fullCData(oldp+43,(vlTOPp->tcpip_top__DOT__mac_rx_to_arp_rx_packet_data),4);
        tracep->fullBit(oldp+44,(vlTOPp->tcpip_top__DOT__mac_rx_to_ip_rx_bad_packet_en));
        tracep->fullBit(oldp+45,(vlTOPp->tcpip_top__DOT__mac_rx_to_ip_rx_bad_packet));
        tracep->fullBit(oldp+46,(vlTOPp->tcpip_top__DOT__mac_rx_to_ip_rx_new_packet_en));
        tracep->fullCData(oldp+47,(vlTOPp->tcpip_top__DOT__mac_rx_to_ip_rx_packet_data),4);
        tracep->fullBit(oldp+48,(vlTOPp->tcpip_top__DOT__arp_rx_new_packet));
        tracep->fullBit(oldp+49,(vlTOPp->tcpip_top__DOT__arp_rx_need_reply));
        tracep->fullIData(oldp+50,(vlTOPp->tcpip_top__DOT__arp_rx_receive_ip),32);
        tracep->fullQData(oldp+51,(vlTOPp->tcpip_top__DOT__arp_rx_receive_mac),48);
        tracep->fullBit(oldp+53,(vlTOPp->tcpip_top__DOT__arp_rx_arp_rx_busy));
        tracep->fullBit(oldp+54,(vlTOPp->tcpip_top__DOT__arp_tx_lookup_done));
        tracep->fullBit(oldp+55,(vlTOPp->tcpip_top__DOT__arp_tx_lookup_result));
        tracep->fullQData(oldp+56,(vlTOPp->tcpip_top__DOT__arp_tx_lookup_mac),48);
        tracep->fullBit(oldp+58,(vlTOPp->tcpip_top__DOT__arp_tx_arp_packet_en));
        tracep->fullCData(oldp+59,(vlTOPp->tcpip_top__DOT__arp_tx_arp_packet_data),4);
        tracep->fullBit(oldp+60,(vlTOPp->tcpip_top__DOT__arp_tx_arp_tx_busy));
        tracep->fullBit(oldp+61,(vlTOPp->tcpip_top__DOT__ip_rx_drop_packet));
        tracep->fullBit(oldp+62,(vlTOPp->tcpip_top__DOT__ip_rx_ip_rx_busy));
        tracep->fullBit(oldp+63,(vlTOPp->tcpip_top__DOT__ip_rx_new_segment));
        tracep->fullCData(oldp+64,(vlTOPp->tcpip_top__DOT__ip_rx_segment_type),8);
        tracep->fullCData(oldp+65,(vlTOPp->tcpip_top__DOT__ip_rx_segment_data),4);
        tracep->fullBit(oldp+66,(vlTOPp->tcpip_top__DOT__test_phy0__DOT__i_rx_clk));
        tracep->fullBit(oldp+67,(vlTOPp->tcpip_top__DOT__test_phy0__DOT__i_tx_clk));
        tracep->fullBit(oldp+68,(vlTOPp->tcpip_top__DOT__test_phy0__DOT__i_rstn));
        tracep->fullBit(oldp+69,(vlTOPp->tcpip_top__DOT__test_phy0__DOT__i_mii_tx_er));
        tracep->fullBit(oldp+70,(vlTOPp->tcpip_top__DOT__test_phy0__DOT__i_mii_tx_en));
        tracep->fullCData(oldp+71,(vlTOPp->tcpip_top__DOT__test_phy0__DOT__i_mii_tx_data),4);
        tracep->fullBit(oldp+72,(vlTOPp->tcpip_top__DOT__test_phy0__DOT__i_mdc));
        tracep->fullBit(oldp+73,(vlTOPp->tcpip_top__DOT__test_phy0__DOT__i_mdio));
        tracep->fullBit(oldp+74,(vlTOPp->tcpip_top__DOT__test_phy0__DOT__o_mii_rx_er));
        tracep->fullBit(oldp+75,(vlTOPp->tcpip_top__DOT__test_phy0__DOT__o_mii_rx_dv));
        tracep->fullCData(oldp+76,(vlTOPp->tcpip_top__DOT__test_phy0__DOT__o_mii_rx_data),4);
        tracep->fullBit(oldp+77,(vlTOPp->tcpip_top__DOT__test_phy0__DOT__o_mii_rx_crs));
        tracep->fullBit(oldp+78,(vlTOPp->tcpip_top__DOT__test_phy0__DOT__o_mii_rx_col));
        tracep->fullBit(oldp+79,(vlTOPp->tcpip_top__DOT__test_phy0__DOT__o_mii_mdio));
        tracep->fullIData(oldp+80,(vlTOPp->tcpip_top__DOT__test_phy0__DOT__tx_index),32);
        tracep->fullIData(oldp+81,(vlTOPp->tcpip_top__DOT__test_phy0__DOT__rx_index),32);
        tracep->fullCData(oldp+82,(vlTOPp->tcpip_top__DOT__test_phy0__DOT__frame_done),3);
        tracep->fullBit(oldp+83,(vlTOPp->tcpip_top__DOT__eth_rx_ctrl0__DOT__i_sys_clk));
        tracep->fullBit(oldp+84,(vlTOPp->tcpip_top__DOT__eth_rx_ctrl0__DOT__i_rx_clk));
        tracep->fullBit(oldp+85,(vlTOPp->tcpip_top__DOT__eth_rx_ctrl0__DOT__i_rstn));
        tracep->fullBit(oldp+86,(vlTOPp->tcpip_top__DOT__eth_rx_ctrl0__DOT__i_rx_dv));
        tracep->fullCData(oldp+87,(vlTOPp->tcpip_top__DOT__eth_rx_ctrl0__DOT__i_rx_data),4);
        tracep->fullBit(oldp+88,(vlTOPp->tcpip_top__DOT__eth_rx_ctrl0__DOT__i_rx_er));
        tracep->fullBit(oldp+89,(vlTOPp->tcpip_top__DOT__eth_rx_ctrl0__DOT__i_rx_col));
        tracep->fullBit(oldp+90,(vlTOPp->tcpip_top__DOT__eth_rx_ctrl0__DOT__i_rx_crs));
        tracep->fullBit(oldp+91,(vlTOPp->tcpip_top__DOT__eth_rx_ctrl0__DOT__i_mdio));
        tracep->fullBit(oldp+92,(vlTOPp->tcpip_top__DOT__eth_rx_ctrl0__DOT__o_len_fifo_w_en));
        tracep->fullSData(oldp+93,(vlTOPp->tcpip_top__DOT__eth_rx_ctrl0__DOT__o_frame_len),14);
        tracep->fullBit(oldp+94,(vlTOPp->tcpip_top__DOT__eth_rx_ctrl0__DOT__o_data_fifo_w_en));
        tracep->fullCData(oldp+95,(vlTOPp->tcpip_top__DOT__eth_rx_ctrl0__DOT__o_frame_data),4);
        tracep->fullBit(oldp+96,(vlTOPp->tcpip_top__DOT__eth_rx_ctrl0__DOT__o_mdio));
        tracep->fullBit(oldp+97,(vlTOPp->tcpip_top__DOT__eth_rx_ctrl0__DOT__prev_rx_dv));
        tracep->fullSData(oldp+98,(vlTOPp->tcpip_top__DOT__eth_rx_ctrl0__DOT__frame_lenth),14);
        tracep->fullBit(oldp+99,(vlTOPp->tcpip_top__DOT__eth_rx_ctrl0__DOT__rx_trans_start));
        tracep->fullBit(oldp+100,(vlTOPp->tcpip_top__DOT__eth_rx_ctrl0__DOT__rx_trans_done));
        tracep->fullBit(oldp+101,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__i_rx_clk));
        tracep->fullBit(oldp+102,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__i_sys_clk));
        tracep->fullBit(oldp+103,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__i_rstn));
        tracep->fullBit(oldp+104,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__i_data_fifo_w_en));
        tracep->fullCData(oldp+105,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__i_data_fifo_data),4);
        tracep->fullBit(oldp+106,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__i_data_fifo_r_en));
        tracep->fullBit(oldp+107,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__i_data_fifo_r_stop));
        tracep->fullSData(oldp+108,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__i_data_fifo_r_line),14);
        tracep->fullBit(oldp+109,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__i_len_fifo_w_en));
        tracep->fullSData(oldp+110,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__i_len_fifo_data),14);
        tracep->fullBit(oldp+111,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__i_len_fifo_r_en));
        tracep->fullCData(oldp+112,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__i_len_fifo_r_line),5);
        tracep->fullBit(oldp+113,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__o_data_fifo_r_done));
        tracep->fullBit(oldp+114,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__o_data_fifo_empty));
        tracep->fullBit(oldp+115,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__o_data_fifo_full));
        tracep->fullCData(oldp+116,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__o_data_fifo_data),4);
        tracep->fullBit(oldp+117,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__o_len_fifo_r_done));
        tracep->fullBit(oldp+118,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__o_len_fifo_empty));
        tracep->fullBit(oldp+119,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__o_len_fifo_full));
        tracep->fullSData(oldp+120,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__o_len_fifo_data),14);
        tracep->fullBit(oldp+121,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_data_fifo0__DOT__i_rx_clk));
        tracep->fullBit(oldp+122,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_data_fifo0__DOT__i_sys_clk));
        tracep->fullBit(oldp+123,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_data_fifo0__DOT__i_rstn));
        tracep->fullBit(oldp+124,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_data_fifo0__DOT__i_fifo_w_en));
        tracep->fullCData(oldp+125,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_data_fifo0__DOT__i_data),4);
        tracep->fullBit(oldp+126,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_data_fifo0__DOT__i_fifo_r_en));
        tracep->fullBit(oldp+127,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_data_fifo0__DOT__i_fifo_r_stop));
        tracep->fullSData(oldp+128,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_data_fifo0__DOT__i_fifo_r_len),14);
        tracep->fullBit(oldp+129,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_data_fifo0__DOT__o_fifo_r_done));
        tracep->fullBit(oldp+130,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_data_fifo0__DOT__o_fifo_empty));
        tracep->fullBit(oldp+131,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_data_fifo0__DOT__o_fifo_full));
        tracep->fullCData(oldp+132,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_data_fifo0__DOT__o_data),4);
        tracep->fullSData(oldp+133,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_data_fifo0__DOT__w_ptr),14);
        tracep->fullSData(oldp+134,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_data_fifo0__DOT__r_ptr),14);
        tracep->fullSData(oldp+135,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_data_fifo0__DOT__r_start_ptr),14);
        tracep->fullBit(oldp+136,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_data_fifo0__DOT__last_read));
        tracep->fullIData(oldp+137,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_data_fifo0__DOT__i),32);
        tracep->fullSData(oldp+138,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_data_fifo0__DOT__end_line),14);
        tracep->fullSData(oldp+139,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_data_fifo0__DOT__fifo_r_end_line),14);
        tracep->fullBit(oldp+140,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__i_rx_clk));
        tracep->fullBit(oldp+141,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__i_sys_clk));
        tracep->fullBit(oldp+142,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__i_rstn));
        tracep->fullBit(oldp+143,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__i_fifo_w_en));
        tracep->fullSData(oldp+144,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__i_data),14);
        tracep->fullBit(oldp+145,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__i_fifo_r_en));
        tracep->fullBit(oldp+146,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__i_fifo_r_stop));
        tracep->fullCData(oldp+147,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__i_fifo_r_len),5);
        tracep->fullBit(oldp+148,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__o_fifo_r_done));
        tracep->fullBit(oldp+149,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__o_fifo_empty));
        tracep->fullBit(oldp+150,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__o_fifo_full));
        tracep->fullSData(oldp+151,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__o_data),14);
        tracep->fullSData(oldp+152,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__fifo_q[0]),14);
        tracep->fullSData(oldp+153,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__fifo_q[1]),14);
        tracep->fullSData(oldp+154,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__fifo_q[2]),14);
        tracep->fullSData(oldp+155,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__fifo_q[3]),14);
        tracep->fullSData(oldp+156,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__fifo_q[4]),14);
        tracep->fullSData(oldp+157,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__fifo_q[5]),14);
        tracep->fullSData(oldp+158,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__fifo_q[6]),14);
        tracep->fullSData(oldp+159,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__fifo_q[7]),14);
        tracep->fullSData(oldp+160,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__fifo_q[8]),14);
        tracep->fullSData(oldp+161,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__fifo_q[9]),14);
        tracep->fullSData(oldp+162,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__fifo_q[10]),14);
        tracep->fullSData(oldp+163,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__fifo_q[11]),14);
        tracep->fullSData(oldp+164,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__fifo_q[12]),14);
        tracep->fullSData(oldp+165,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__fifo_q[13]),14);
        tracep->fullSData(oldp+166,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__fifo_q[14]),14);
        tracep->fullSData(oldp+167,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__fifo_q[15]),14);
        tracep->fullSData(oldp+168,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__fifo_q[16]),14);
        tracep->fullSData(oldp+169,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__fifo_q[17]),14);
        tracep->fullSData(oldp+170,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__fifo_q[18]),14);
        tracep->fullSData(oldp+171,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__fifo_q[19]),14);
        tracep->fullSData(oldp+172,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__fifo_q[20]),14);
        tracep->fullSData(oldp+173,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__fifo_q[21]),14);
        tracep->fullSData(oldp+174,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__fifo_q[22]),14);
        tracep->fullSData(oldp+175,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__fifo_q[23]),14);
        tracep->fullCData(oldp+176,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__w_ptr),5);
        tracep->fullCData(oldp+177,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__r_ptr),5);
        tracep->fullCData(oldp+178,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__r_start_ptr),5);
        tracep->fullBit(oldp+179,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__last_read));
        tracep->fullIData(oldp+180,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__i),32);
        tracep->fullCData(oldp+181,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__end_line),5);
        tracep->fullCData(oldp+182,(vlTOPp->tcpip_top__DOT__eth_fifo0__DOT__eth_len_fifo1__DOT__fifo_r_end_line),5);
        tracep->fullBit(oldp+183,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__i_sys_clk));
        tracep->fullBit(oldp+184,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__i_rstn));
        tracep->fullBit(oldp+185,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__i_len_fifo_empty));
        tracep->fullBit(oldp+186,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__i_len_r_done));
        tracep->fullBit(oldp+187,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__i_data_r_done));
        tracep->fullSData(oldp+188,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__i_frame_len),14);
        tracep->fullCData(oldp+189,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__i_frame_data),4);
        tracep->fullBit(oldp+190,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__i_arp_rx_busy));
        tracep->fullBit(oldp+191,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__i_ip_rx_busy));
        tracep->fullBit(oldp+192,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__i_ip_rx_drop));
        tracep->fullBit(oldp+193,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__o_len_fifo_r_en));
        tracep->fullCData(oldp+194,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__o_len_fifo_r_line),5);
        tracep->fullBit(oldp+195,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__o_data_fifo_r_en));
        tracep->fullSData(oldp+196,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__o_data_fifo_r_line),14);
        tracep->fullBit(oldp+197,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__o_data_fifo_r_stop));
        tracep->fullSData(oldp+198,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__o_eth_type),16);
        tracep->fullBit(oldp+199,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__o_bad_packet_en));
        tracep->fullBit(oldp+200,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__o_bad_packet));
        tracep->fullBit(oldp+201,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__o_new_packet_en));
        tracep->fullCData(oldp+202,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__o_packet_data),4);
        tracep->fullCData(oldp+203,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__CUR_STAGE),2);
        tracep->fullCData(oldp+204,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__NXT_STAGE),2);
        tracep->fullSData(oldp+205,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__frame_recieved_cnt),14);
        tracep->fullQData(oldp+206,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__src_mac_latch),48);
        tracep->fullQData(oldp+208,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__dst_mac_latch),48);
        tracep->fullSData(oldp+210,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__eth_type_latch),16);
        tracep->fullBit(oldp+211,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__eth_parse_done));
        tracep->fullSData(oldp+212,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__frame_len_latch),14);
        tracep->fullBit(oldp+213,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__ip_rx_clear));
        tracep->fullBit(oldp+214,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__my_frame));
        tracep->fullBit(oldp+215,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__fcs_data_start));
        tracep->fullBit(oldp+216,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__fcs_check));
        tracep->fullBit(oldp+217,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__fcs_en));
        tracep->fullBit(oldp+218,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__fcs_comp_done));
        tracep->fullIData(oldp+219,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__fcs_comp),32);
        tracep->fullCData(oldp+220,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__frame_prev_latch),4);
        tracep->fullBit(oldp+221,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__fcs_data_cnt));
        tracep->fullCData(oldp+222,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__fcs_data),8);
        tracep->fullBit(oldp+223,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__crc32_0__DOT__i_sys_clk));
        tracep->fullBit(oldp+224,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__crc32_0__DOT__i_rstn));
        tracep->fullCData(oldp+225,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__crc32_0__DOT__i_data),8);
        tracep->fullBit(oldp+226,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__crc32_0__DOT__i_crc_en));
        tracep->fullBit(oldp+227,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__crc32_0__DOT__i_crc_done));
        tracep->fullIData(oldp+228,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__crc32_0__DOT__o_fcs),32);
        tracep->fullIData(oldp+229,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__crc32_0__DOT__lfsr_q),32);
        tracep->fullIData(oldp+230,(vlTOPp->tcpip_top__DOT__mac_rx0__DOT__crc32_0__DOT__lfsr_c),32);
        tracep->fullBit(oldp+231,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__i_sys_clk));
        tracep->fullBit(oldp+232,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__i_rstn));
        tracep->fullBit(oldp+233,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__i_new_packet));
        tracep->fullCData(oldp+234,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__i_packet_data),4);
        tracep->fullBit(oldp+235,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__i_bad_packet_en));
        tracep->fullBit(oldp+236,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__i_bad_packet));
        tracep->fullBit(oldp+237,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__i_arp_tx_busy));
        tracep->fullBit(oldp+238,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__o_new_packet));
        tracep->fullBit(oldp+239,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__o_arp_need_reply));
        tracep->fullIData(oldp+240,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__o_arp_receive_ip),32);
        tracep->fullQData(oldp+241,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__o_arp_receive_mac),48);
        tracep->fullBit(oldp+243,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__o_arp_rx_busy));
        tracep->fullSData(oldp+244,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__hardware_type_latch),16);
        tracep->fullSData(oldp+245,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__protocol_type_latch),16);
        tracep->fullSData(oldp+246,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__opcode_latch),16);
        tracep->fullQData(oldp+247,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__src_mac_latch),48);
        tracep->fullIData(oldp+249,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__src_ip_latch),32);
        tracep->fullIData(oldp+250,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__dest_ip_latch),32);
        tracep->fullCData(oldp+251,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__arp_recieve_cnt),6);
        tracep->fullBit(oldp+252,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__new_packet_latch));
        tracep->fullCData(oldp+253,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__CUR_STAGE),2);
        tracep->fullCData(oldp+254,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__NXT_STAGE),2);
        tracep->fullBit(oldp+255,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__correct_packet));
        tracep->fullBit(oldp+256,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__gather_done));
        tracep->fullBit(oldp+257,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__arp_done));
        tracep->fullBit(oldp+258,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__my_arp_packet));
        tracep->fullBit(oldp+259,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__arp_request));
        tracep->fullBit(oldp+260,(vlTOPp->tcpip_top__DOT__arp_rx0__DOT__arp_reply));
        tracep->fullBit(oldp+261,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__i_sys_clk));
        tracep->fullBit(oldp+262,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__i_rstn));
        tracep->fullBit(oldp+263,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__i_lookup_en));
        tracep->fullIData(oldp+264,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__i_lookup_ip),32);
        tracep->fullBit(oldp+265,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__i_rx_new_packet));
        tracep->fullBit(oldp+266,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__i_need_reply));
        tracep->fullIData(oldp+267,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__i_receive_ip),32);
        tracep->fullQData(oldp+268,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__i_receive_mac),48);
        tracep->fullBit(oldp+270,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__o_lookup_done));
        tracep->fullBit(oldp+271,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__o_lookup_result));
        tracep->fullQData(oldp+272,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__o_lookup_mac),48);
        tracep->fullBit(oldp+274,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__o_arp_packet_en));
        tracep->fullCData(oldp+275,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__o_arp_packet_data),4);
        tracep->fullBit(oldp+276,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__o_arp_tx_busy));
        tracep->fullCData(oldp+277,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__CUR_STAGE),2);
        tracep->fullCData(oldp+278,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__NXT_STAGE),2);
        tracep->fullQData(oldp+279,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__src_mac_latch),48);
        tracep->fullIData(oldp+281,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__src_ip_latch),32);
        tracep->fullBit(oldp+282,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__mac_unkwown));
        tracep->fullIData(oldp+283,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__lookup_ip_latch),32);
        tracep->fullBit(oldp+284,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__arp_cache_w_en));
        tracep->fullCData(oldp+285,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__arp_send_cnt),6);
        tracep->fullBit(oldp+286,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__arp_send_done));
        tracep->fullBit(oldp+287,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__arp_cache0__DOT__i_sys_clk));
        tracep->fullBit(oldp+288,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__arp_cache0__DOT__i_rstn));
        tracep->fullBit(oldp+289,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__arp_cache0__DOT__i_lookup_en));
        tracep->fullIData(oldp+290,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__arp_cache0__DOT__i_lookup_ip),32);
        tracep->fullBit(oldp+291,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__arp_cache0__DOT__i_cache_w_en));
        tracep->fullIData(oldp+292,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__arp_cache0__DOT__i_cache_w_ip),32);
        tracep->fullQData(oldp+293,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__arp_cache0__DOT__i_cache_w_mac),48);
        tracep->fullBit(oldp+295,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__arp_cache0__DOT__o_lookup_done));
        tracep->fullBit(oldp+296,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__arp_cache0__DOT__o_lookup_result));
        tracep->fullQData(oldp+297,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__arp_cache0__DOT__o_lookup_mac),48);
        tracep->fullQData(oldp+299,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__arp_cache0__DOT__arp_mac_queue[0]),48);
        tracep->fullQData(oldp+301,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__arp_cache0__DOT__arp_mac_queue[1]),48);
        tracep->fullQData(oldp+303,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__arp_cache0__DOT__arp_mac_queue[2]),48);
        tracep->fullQData(oldp+305,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__arp_cache0__DOT__arp_mac_queue[3]),48);
        tracep->fullQData(oldp+307,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__arp_cache0__DOT__arp_mac_queue[4]),48);
        tracep->fullIData(oldp+309,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__arp_cache0__DOT__arp_ip_queue[0]),32);
        tracep->fullIData(oldp+310,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__arp_cache0__DOT__arp_ip_queue[1]),32);
        tracep->fullIData(oldp+311,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__arp_cache0__DOT__arp_ip_queue[2]),32);
        tracep->fullIData(oldp+312,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__arp_cache0__DOT__arp_ip_queue[3]),32);
        tracep->fullIData(oldp+313,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__arp_cache0__DOT__arp_ip_queue[4]),32);
        tracep->fullCData(oldp+314,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__arp_cache0__DOT__queue_w_ptr),3);
        tracep->fullCData(oldp+315,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__arp_cache0__DOT__a),3);
        tracep->fullIData(oldp+316,(vlTOPp->tcpip_top__DOT__arp_tx0__DOT__arp_cache0__DOT__b),32);
        tracep->fullBit(oldp+317,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__i_sys_clk));
        tracep->fullBit(oldp+318,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__i_rstn));
        tracep->fullBit(oldp+319,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__i_new_packet));
        tracep->fullCData(oldp+320,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__i_ip_data),4);
        tracep->fullBit(oldp+321,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__i_bad_packet_en));
        tracep->fullBit(oldp+322,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__i_bad_packet));
        tracep->fullBit(oldp+323,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__o_drop_packet));
        tracep->fullBit(oldp+324,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__o_ip_rx_busy));
        tracep->fullBit(oldp+325,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__o_new_segment));
        tracep->fullCData(oldp+326,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__o_segment_type),8);
        tracep->fullCData(oldp+327,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__o_segment_data),4);
        tracep->fullCData(oldp+328,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__CUR_STAGE),2);
        tracep->fullCData(oldp+329,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__NXT_STAGE),2);
        tracep->fullCData(oldp+330,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__ip_ver_latch),4);
        tracep->fullCData(oldp+331,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__ihl_latch),4);
        tracep->fullCData(oldp+332,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__flag_latch),3);
        tracep->fullSData(oldp+333,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__frag_offset_latch),13);
        tracep->fullCData(oldp+334,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__protocol_latch),8);
        tracep->fullSData(oldp+335,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__checksum_latch),16);
        tracep->fullIData(oldp+336,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__src_ip_latch),32);
        tracep->fullIData(oldp+337,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__dst_ip_latch),32);
        tracep->fullSData(oldp+338,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__rx_cnt),14);
        tracep->fullSData(oldp+339,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__checksum_temp),16);
        tracep->fullSData(oldp+340,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__checksum_sum),16);
        tracep->fullCData(oldp+341,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__checksum_cnt),2);
        tracep->fullIData(oldp+342,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__checksum_extend),17);
        tracep->fullBit(oldp+343,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__packet_en_prev));
        tracep->fullBit(oldp+344,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__header_done));
        tracep->fullBit(oldp+345,(vlTOPp->tcpip_top__DOT__ip_rx0__DOT__check_failed));
        tracep->fullQData(oldp+346,(0x107c4fa2a003ULL),48);
        tracep->fullIData(oldp+348,(0xc0a80100U),32);
        tracep->fullQData(oldp+349,(0x183e043329ULL),48);
        tracep->fullIData(oldp+351,(0xc0a80106U),32);
        tracep->fullIData(oldp+352,(4U),32);
        tracep->fullIData(oldp+353,(0x2f70U),32);
        tracep->fullIData(oldp+354,(0xeU),32);
        tracep->fullIData(oldp+355,(0x18U),32);
        tracep->fullCData(oldp+356,(0U),2);
        tracep->fullCData(oldp+357,(1U),2);
        tracep->fullCData(oldp+358,(2U),2);
        tracep->fullCData(oldp+359,(3U),2);
        tracep->fullCData(oldp+360,(5U),3);
        tracep->fullCData(oldp+361,(6U),8);
        tracep->fullCData(oldp+362,(0x11U),8);
        tracep->fullCData(oldp+363,(1U),8);
    }
}
